### ISSUE TITLE
The path is not of legal form

### ISSUE THREAD

**Issue by HelenAtGitHub** [sergeyshushlyapin/Sitecore.FakeDb#183] opened 2017-07-12 11:41 UTC
This is the first time I tried FakeDb and may run into wrong way. When I run the sample code from https://github.com/sergeyshushlyapin/Sitecore.FakeDb/wiki , it returns an error "The path is not of legal form" on code below: 
using (var db = new Db
    {
      new DbItem("Home") { { "Title", "Welcome!" } }
    })
I also got the source code from github and build successfully on local. Run the same testing case in Examples.GettingStarted.HowToCreateSimpleItem(). After that, it returned null reference on the line below in Sitecore.FakeDb.Db.Db(string databaseName) method. 
      this.database = Database.GetDatabase(databaseName);
Your guidance would be much appreciated.

**Comment by sergeyshushlyapin** [comment] 2017-07-13 04:21
Could you please share the full test that fails and check you've [installed FakeDb correctly](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/wiki/Installation)? Please also ensure you've referenced all the required Sitecore assemblies (listed on the installation page).

**Comment by HelenAtGitHub** [comment] 2017-07-13 09:25
Actually, after updating the LicenseFile setting to "/license.xml" in the App.config, it works fine. But the point is we are using MSTest not NUnit3.

**Comment by sergeyshushlyapin** [comment] 2017-07-14 06:30
> it works fine. But the point is we are using MSTest not NUnit3.

Not sure I got this... IIRC, MSTest uses another directory to run tests. You may experiment with [configuration](https://stackoverflow.com/questions/5710167/ms-test-getting-executing-testlocation), or set absolute path to the license file. You may also try the `Additional files to include` setting as described in [wiki](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/wiki/Installation).

**Comment by HelenAtGitHub** [comment] 2017-07-17 17:03
I download the source code from https://github.com/sergeyshushlyapin/Sitecore.FakeDb
, when I run a testing against Examples.GettingStarted.HowToCreateSimpleItem() method, then got an error as below. 

![error](https://user-images.githubusercontent.com/13775804/28279953-bf214388-6b54-11e7-84b7-a93db38df3b6.PNG)

**Comment by sergeyshushlyapin** [comment] 2018-10-26 15:57
Cannot reproduce. Please provide detailed scenario. Closing this for now.

**Closed by sergeyshushlyapin** 2018-10-26 15:57 UTC
