### ISSUE TITLE
Using provided NUnit runner in JetBrains TeamCity

### ISSUE THREAD

**Issue by vtml** [sergeyshushlyapin/Sitecore.FakeDb#30] opened 2014-12-09 02:59 UTC
I am seeing a lot of warning / errors when using JetBrains TeamCity NUnit runner when using Sitecore.FakeDb. The most simplest test as provided in the wiki's example will cause an error immediately.

[ManagedPoolThread #15] WARN  JetBrains.Container.Log4netDefaultLoggerInitializer - Unhandled exception in current domain: System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain., , (null)

This error causes TeamCity's DotCover code coverage to hang indefinitely as well.
This only occurs in TeamCity, and runs perfectly fine if I use NUnit from the official source, as well as using ReSharper in Visual Studio to run the Tests.

It will be good if anyone has any solution, otherwise I am going to try using an external runner.
http://www.tellingmachine.com/post/Running-NUnit-tests-externally-without-a-TeamCity-agent-and-synchronizing-execution-time-and-test-results-with-a-TeamCity-build.aspx
Then somehow use the provided Code Coverage tool in TeamCity as well.

**Comment by mickyjtwin** [comment] 2015-02-01 22:08
> We've run into this issue a few times. In our case it was some components our code was using that started a separate thread that continued to run even after tests finished.
We've checked the 'Run process per assemlby' and removed the code coverage of 'Jetbrains dotCover' and it worked...

They also state that adding dotCover back in breaks again.

Seems that the code:
```c#
[Fact]
public void HowToCreateSimpleItem()
{
  using (var db = new Db
    {
      new DbItem("Home") { { "Title", "Welcome!" } }
    })
  {
    Sitecore.Data.Items.Item home = db.GetItem("/sitecore/content/home");
    Xunit.Assert.Equal("Welcome!", home["Title"]);
  }
}
```
Sitecore's kernel dll is opening a new thread, which is not being closed

**Comment by sergeyshushlyapin** [comment] 2015-02-03 14:26
When I run my tests in xUnit Test Explorer I see **21** errors in console:

    System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain.
    This can happen if the test(s) started a thread but did not stop it.
    Make sure that all the threads started by the test(s) are stopped before completion.

> the test(s) started a thread but did not stop it.

I suppose that is the indication of the problem.

The `ManagedThreadPool`'s static constructor creates **20** of them which is the default amount of the `MaxWorkerThreads` setting. After resetting the setting to 0 I see **only one** error message in console.

    <setting name="MaxWorkerThreads" value="0" />

Trying to find the source of the last error.

**Comment by sergeyshushlyapin** [comment] 2015-02-12 10:51
The latest unload domain exceptions are caused by the `Sitecore.IO.FileWatcher` class from the `Sitecore.Kernel` assembly which starts a thread with infinite loop in the `InitializeWorker` method. The method is called by the `LicenseWatcher` which is called from `nexus`.

Unfortunately there is no way to workaround it in scope of `FakeDb`. The issue is registered for Sitecore, but there is no ETA so far.

@vtml, @mickyjtwin - could you please check if setting the `MaxWorkerThreads` setting to `0` can  improve the situation?

Thanks!

**Comment by vtml** [comment] 2015-02-12 22:56
Hi @sergeyshushlyapin , that didn't work unfortunately.
It looks like the only solution worth trying is to install code coverage tool on developer's PC's as a work around for now.

**Comment by sergeyshushlyapin** [comment] 2015-03-16 11:18
Good news guys,
The issue has been fixed in 7.2 update-4 (approx. end of March). I've checked it, the `System.AppDomainUnloadedException` has gone.

Waiting for your feedback once the update is public.

**Comment by vtml** [comment] 2015-03-16 22:16
Will there be an update for 7.5 as well ?

**Comment by sergeyshushlyapin** [comment] 2015-03-20 09:06
as far as I know 7.5 is some kind of 'intermediate' version between 7.2 and 8 so I wouldn't expect a lot of update releases here. But it definitely should appear in the coming 8.0 updates.

**Comment by sergeyshushlyapin** [comment] 2015-03-25 16:41
I'd like to close the issue, if you have no objection. Please let me know whether the new Sitecore version can solve it.

**Closed by sergeyshushlyapin** 2015-03-25 16:41 UTC
Labels: bug

**Comment by vtml** [comment] 2015-05-15 02:21
Just want to confirm that this is no longer an issue for Sitecore 8 Update 3.

**Comment by sergeyshushlyapin** [comment] 2015-05-15 07:14
That is great! Thanks.
