### ISSUE TITLE
Upgradinig to 1.7 causes the following error with SC 8.1

### ISSUE THREAD

**Issue by mikeedwards83** [sergeyshushlyapin/Sitecore.FakeDb#189] opened 2017-10-12 19:55 UTC
After upgrading to 1.7 from 1.2 I get the following error, have you seen this before?

`System.TypeLoadException : Could not load type 'Sitecore.Reflection.INexusDataApiEx' from assembly 'Sitecore.Kernel, Version=8.1.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at Sitecore.Reflection.ReflectionUtil.CreateObject(String assembly, String className, Object[] parameters)
   at Sitecore.Reflection.ReflectionUtil.CreateObject(String typeName, Object[] parameters)
   at Sitecore.Reflection.Nexus.GetApi[T](String typeName, T& api)
   at Sitecore.Data.Engines.DataCommands.ResolvePathCommand.DoExecute()
   at Sitecore.Data.Engines.EngineCommand`2.Execute()
   at Sitecore.Data.Engines.DataEngine.ResolvePath(String itemPath)
   at Sitecore.Data.Managers.ItemProvider.ResolvePath(String itemPath, Database database)
   at Sitecore.Data.Managers.ItemProvider.GetItem(String itemPath, Language language, Version version, Database database, SecurityCheck securityCheck)
   at Sitecore.Data.Managers.ItemManager.GetItem(String itemPath, Language language, Version version, Database database)
   at Sitecore.Data.Database.GetItem(String path)``

**Comment by mikeedwards83** [comment] 2017-10-12 20:05
Further testing shows that this problem only occurs from v1.5, v1.4.1 is ok

**Comment by sergeyshushlyapin** [comment] 2017-10-14 08:26
It was a major internal change introduced in [v1.5.0](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/issues/168). Big chunck of FakeDb logic was moved from commands to providers which allowed to simplify it significantly. Since all the old functional tests were green, the version was considered as stable and released.

I've never meet this error before. Could you please share a failing test to reproduce the problem on FakeDb side? Thanks.

**Comment by mikeedwards83** [comment] 2017-11-21 18:18
@sergeyshushlyapin sorry for the slow reply. All the tests in this class fail https://github.com/mikeedwards83/Glass.Mapper/blob/8f4506a14b7c1cd3f9179ed6459741c73fa7ea1a/Tests/Integration%20Tests/Sitecore/Glass.Mapper.Sc.Integration/DataMappers/SitecoreFieldStringMapperFixture.cs

**Comment by sergeyshushlyapin** [comment] 2018-11-01 13:45
Looks like this issue is not actual anymore. At least I managed to build Glass against Sitecore 8.1 (locally) and the mentioned tests passed. Closing.

**Closed by sergeyshushlyapin** 2018-11-01 13:45 UTC
